In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = pd.read_csv('housing_price_dataset.csv')

In [74]:
df.head()

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [75]:
df.columns

Index(['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt',
       'Price'],
      dtype='object')

In [76]:
df.isnull().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [77]:
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

from sklearn.preprocessing import LabelEncoder
from sklearn import tree, svm
from sklearn.model_selection import cross_val_score, train_test_split, cross_val_predict, KFold
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix, precision_recall_curve, roc_curve 
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier,RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.neighbors  import KNeighborsClassifier

In [78]:
le = LabelEncoder()

In [79]:
df['Neighborhood'] = le.fit_transform(df['Neighborhood'])

In [80]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Créez une instance de StandardScaler
sc = StandardScaler()

# Remodelez votre tableau 1D en tableau 2D
df['SquareFeet'] = sc.fit_transform(df['SquareFeet'].values.reshape(-1, 1))

In [81]:
df.head()

   SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0    0.207861         4          1             0       1969  215355.283618
1    0.786480         3          2             0       1980  195014.221626
2   -0.254340         2          1             1       1970  306891.012076
3    0.499777         2          1             2       1996  206786.787153
4    0.214811         5          2             1       2001  272436.239065

In [82]:
X = df.drop(['Price'], axis=1)
y = df['Price']

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [84]:
import tensorflow as tf
from tensorflow import keras
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [85]:
from xgboost import XGBRegressor as xGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
xgb = xGBRegressor() 
xgb.fit(X_train,y_train)
xgbtd=xgb.predict(X_test)
xgbr2=r2_score(y_test,xgbtd)

In [86]:
xgbr2

0.5559120967214524

In [92]:
gbl = GradientBoostingRegressor()
gbl.fit(X_train,y_train)
gbltd=gbl.predict(X_test)
gblr2=r2_score(y_test,gbltd)
rmse = mean_squared_error(y_test, gbltd,squared=False)
print("RMSE:", rmse)

RMSE: 49438.12870556539

In [88]:
gblr2

0.5741901691943013

In [89]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)
rftd=rf.predict(X_test)
rfr2=r2_score(y_test,rftd)

In [90]:
rfr2

0.5190125913112731

In [91]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the neural network model
model = Sequential()

# Add input layer
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))

# Add one or more hidden layers
model.add(Dense(units=32, activation='relu'))

# Add output layer
model.add(Dense(units=1, activation='linear'))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

# Make predictions on the test set
nn_predictions = model.predict(X_test)

# Evaluate the model
nn_loss, nn_mae = model.evaluate(X_test, y_test)

# Print R-squared score (optional)
from sklearn.metrics import r2_score
nn_r2 = r2_score(y_test, nn_predictions)
print(f"R-squared Score: {nn_r2}")

Epoch 1/20
1250/1250 [==============================] - 3s 2ms/step - loss: 16732955648.0000 - mae: 100155.6328 - val_loss: 5717893120.0000 - val_mae: 61625.7969
Epoch 2/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5783658496.0000 - mae: 62096.2617 - val_loss: 5697689600.0000 - val_mae: 61505.8828
Epoch 3/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5765512704.0000 - mae: 61984.1914 - val_loss: 5694700032.0000 - val_mae: 61463.0352
Epoch 4/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5746380800.0000 - mae: 61880.2383 - val_loss: 5655528448.0000 - val_mae: 61261.3438
Epoch 5/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5725096448.0000 - mae: 61746.3359 - val_loss: 5635639808.0000 - val_mae: 61144.8516
Epoch 6/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5702935040.0000 - mae: 61624.3281 - val_loss: 5611918336.0000 - val_mae: 61005.4844
Epoch 7/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5679687680.0000 - mae: 61492.9805 - val_loss: 5588449280.0000 - val_mae: 60867.5859
Epoch 8/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5654690816.0000 - mae: 61344.5586 - val_loss: 5592747520.0000 - val_mae: 60873.0430
Epoch 9/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5625204736.0000 - mae: 61158.7969 - val_loss: 5538779648.0000 - val_mae: 60573.2656
Epoch 10/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5596010496.0000 - mae: 61011.0391 - val_loss: 5504092672.0000 - val_mae: 60356.7695
Epoch 11/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5562376704.0000 - mae: 60806.2266 - val_loss: 5470517248.0000 - val_mae: 60151.6289
Epoch 12/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5522789888.0000 - mae: 60569.3711 - val_loss: 5424137728.0000 - val_mae: 59883.8516
Epoch 13/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5477735424.0000 - mae: 60298.8242 - val_loss: 5374784512.0000 - val_mae: 59598.7695
Epoch 14/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5425933824.0000 - mae: 60005.8633 - val_loss: 5326051840.0000 - val_mae: 59306.1562
Epoch 15/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5359333888.0000 - mae: 59610.6641 - val_loss: 5241667584.0000 - val_mae: 58796.6523
Epoch 16/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5275201536.0000 - mae: 59107.7969 - val_loss: 5148340224.0000 - val_mae: 58224.4023
Epoch 17/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5169382912.0000 - mae: 58471.2773 - val_loss: 5033222144.0000 - val_mae: 57527.9102
Epoch 18/20
1250/1250 [==============================] - 2s 2ms/step - loss: 5028001280.0000 - mae: 57603.3555 - val_loss: 4859552768.0000 - val_mae: 56449.3828
Epoch 19/20
1250/1250 [==============================] - 2s 2ms/step - loss: 4830735360.0000 - mae: 56385.5859 - val_loss: 4624931328.0000 - val_mae: 54977.0430
Epoch 20/20
1250/1250 [==============================] - 2s 2ms/step - loss: 4551042560.0000 - mae: 54617.5312 - val_loss: 4296142848.0000 - val_mae: 52862.4062
313/313 [==============================] - 0s 1ms/step
313/313 [==============================] - 0s 1ms/step - loss: 4296142848.0000 - mae: 52862.4062
R-squared Score: 0.2515366467250695